[package]
name = "bays_packages"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
rand_distr = "0.4"
ndarray = "0.15"
ndarray-rand = "0.14"
statrs = "0.15.0"
csv = "1.1"
plotters = "0.3"

[profile.dev]
# warnings = "off"
